### ISSUE TITLE
macOS: "getting started" instructions failing to install drivers

### ISSUE THREAD

**Issue by gomesfernanda** [bblfsh/documentation#102]
I was following the Getting Started instructions to install bblfshd and the drivers.
First I typed
`$ docker run -d --name bblfshd --privileged -p 9432:9432 -v /tmp/bblfshd:/var/lib/bblfshd bblfsh/bblfshd`

And everything seemed ok . Response for `docker logs bblfshd` :
```
time="2017-10-24T09:02:06Z" level=info msg="bblfshd version: v2.1.0 (build: 2017-10-11T14:17:00+0000)"
time="2017-10-24T09:02:06Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2017-10-24T09:02:06Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2017-10-24T09:02:06Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
```

However, when I typed
`$ docker exec -it bblfshd bblfshctl driver install --all`

I got as return
```
Installing python driver language from "docker://bblfsh/python-driver:latest"... Error
Error, mkdir /var/lib/bblfshd/tmp/image773185457: permission denied
Installing java driver language from "docker://bblfsh/java-driver:latest"... Error
Error, mkdir /var/lib/bblfshd/tmp/image255471964: permission denied
```

I don't know if this relates to the [Issue #97](https://github.com/bblfsh/documentation/issues/97) opened by Alex.

**Comment by abeaumont** [comment]
Aftere fixing permissions at https://github.com/bblfsh/bblfshd/pull/127, there's still a problem remaining, which is related to the `python-driver`, so I've created a more specific issue at https://github.com/bblfsh/python-driver/issues/128.

Closing this one.
