### ISSUE TITLE
Python AST => UAST: Missing UAST Nodes and other things to consider

### ISSUE THREAD

**Issue by juanjux** [bblfsh/documentation#13]
# Python AST => UAST: Missing UAST Nodes and other things to consider

## Missing nodes

* Operators: didn't find any reference on the docs (I'm going by: https://godoc.org/github.com/bblfsh/sdk/uast). The Python AST has nodes for these operators (and others like the Index that I comment as their on items on this list):

```
	Compare          => (comparators) .ops[list] = Eq | NotEq | Lt | LtE | Gt | GtE | Is | IsNot | In | NotIn
	BoolOp           => .boolop = And | Or
	BinOp            => .op = Add | Sub | Mult | MatMult | Div | Mod | Pow | LShift | RShift | BitOr |
	                          BitXor | BitAnd | FloorDiv
	UnaryOp          => .unaryop = Invert | Not | UAdd | USub
```

* FunctionInvocation, FunctionInvocation, FunctionInvocationName, FunctionInvocationArgumentList, FuncionInvocationArgument, FunctionInvocationArgumentDefaultValue (and MethodInvocationArgumentDefaultValue). 

* FunctionInvocationObject for languages that support emulating method calls with functions like C#, Ruby, D, Nim, etc (3.toString, etc).

* LambdaExpression, LambdaArguments, LambdaBody

* BoolLiteral

* UnicodeString or RawString or ByteString and decide what the default String is

* Compount literals (with child nodes): ComplexLiteral, TupleLiteral, ListLiteral, SetLiteral, DictLiteral (or HashLiteral), FormattedStringLiteral or ParametrizedStringLiteral.

* Async / Await or Join and/or the more specific (in Python) AsyncDef, AsyncFor and AsyncWhile.

* Comprehension (ListComprehension, DictComprehension, SetComprehension).

* GeneratorExpression, Yield, YieldFrom.

* IfExpression (a = 3 if condition else 4 in Python or the a = condition? Value: elseValue or C derived languages).

* ForEach, ForEachIter, ForEachTarget

* ForElse, WhileElse, DoWhileElse: in Python and other languages loops can have an "else" clause that will be run if the loops reach the end (by iterating over everything in case of the for or the condition being false in for the while) without a break. Could be clearer if we call it “ForComplete, WhileComplete, etc”.

* TryElse: Python exceptions can have an else "If there is no exception run this". Could be called “TryNoException”.

* BlockScopeResource, BlockScopeResourceObject, BlockScopeResourceAlias: for representing Python (and other languages) blocks with a resorce that will be freed at the end (with open("file.txt") as f:).

* Delete

* Print / Echo is a keyword in a lot of languages.

* Keyword for other very language-specific keywords with a SimpleIdentifier subnode and optionally argument lists. For example in Python we could use it for: global, nonlocal, exec, eval,  ellipsis.

* ExpandOperator (* in Python to expand a list).

* Annotation (like argument or assigment annotations in Python).

* AugmentedAssigment (+=, -+, etc).

* Unary[Pre|Post]Increase / Unary[Pre|Post]Decrease (a++, --a, etc). Or UnaryOperator with a IncreaseOperator or DecreaseOperator child node (Python doesn’t have this but C-derived languages do).

* IndexExpression, IndexSliceExpression, IndexCompoundExpression. In Python we have Subscript ([]) that can have an Index child node ([3]) or a Slice child node with lower, upper, step ([3:2:1]) or a ExtSlice  that can have any number or Index or Slice childs ([3,2:4,2:7,3…]).

## Other stuff

* Comments and Whitespace: I added them as properties of other "real" nodes (nodes.leading_comments, nodes.sameline_comments). This is the approach that two other FST are using, they could certainly could be converted to nodes with some effort but we should consider if they’re better represented as this (this structure of noops as node properties makes it pretty easy to recover the original code).

* Python AST nodes that assign or read (so most of them) have a "ctx" or “expression context” field that indicates if the node is written to (“Store”), is read (“Load”), or deleted (“Del”). While it’s interesting it also can be 100% inferred so I omitted that.

## Python function/method calls

The Call node in Python is used for both methods and functions, but there are differences that will all us to differentiate normal calls from method calls:

* The AST for a method has this form on its Call->func node:

```json
"func": {"ast_type": "Attribute",
            "attr": "update",
            "value": {"ast_type": "Name", "id": "retDict"}
           }
```    

* While normal non method calls have this form:

```json
"func": {"ast_type": "Name",  "id": "export_dict"}
```                                        
The differences that will allow us to identify one from the other are:

* The method has the "Attribute" ast_type while the function has simply “Name”.

* The method has a "value" subnode and Call.func.value.id is the name of the object on which the call is being made.

* The method name is on the Call.func.attr node whiile on the func is on Call.func.id. 

With this it will be easy to identify one or the other with the caveat that non-method functions used with the module name (example: ast.parse()) use the "method" form. This makes sense because in Python modules *are* (singleton) objects but if the function was imported as “from ast import parse” then it uses the second for. So we could just keep them as MethodCalls or I could add some intelligence to the AST exporter to find if the left side of the dot is an imported module and mark those as normal functions. This could fail in some cases because in Python you can play and modify the import system but those cases should be rare and we could fallback to leave them as Method in that case.

PS: this site is the best description of Python AST nodes: 
https://docs.python.org/3/library/ast.html

**Comment by juanjux** [comment]
PS: this site is the best description of Python AST nodes: 

https://docs.python.org/3/library/ast.html

**Comment by juanjux** [comment]
Another thing I forgot to add: I don't find the definition of operators in the current UAST (I'm going by: https://godoc.org/github.com/bblfsh/sdk/uast). 

The Python AST has nodes for:

```
	Compare          => (comparators) .ops[list] = Eq | NotEq | Lt | LtE | Gt | GtE | Is | IsNot | In | NotIn
	BoolOp           => .boolop = And | Or
	BinOp            => .op = Add | Sub | Mult | MatMult | Div | Mod | Pow | LShift | RShift | BitOr |
	                          BitXor | BitAnd | FloorDiv
	UnaryOp          => .unaryop = Invert | Not | UAdd | USub
```

**Comment by abeaumont** [comment]
Closing this, it's just a status reference
