### ISSUE TITLE
Minor documentation issues on the annotations page

### ISSUE THREAD

**Issue by eiso** [bblfsh/documentation#142]
Page: https://doc.bblf.sh/driver/annotations.html

A few minor issues on this page:

- "When in doubt..." section has a formatting issue
- The community slack channel invite link is expired/wrong one (@marnovo) can provide the correct one
- Every header in this page is somehow a link to https://doc.bblf.sh/driver/sdk.html

**Comment by juanjux** [comment]
@eiso 

- "When in doubt..." fixing it.
- "Slack link" @marnovo could you provide the link?
- "Every header..." You mean the links in the "Introduction" section? The page is the right one for those links, but they should link to the right sections inside, I'll fix it.

**Comment by juanjux** [comment]
Not closing yet since the Slack link is still not updated.

**Comment by marnovo** [comment]
@juanjux correct/updated link inviting to our Slack: https://join.slack.com/t/sourced-community/shared_invite/enQtMjc4Njk5MzEyNzM2LTFjNzY4NjEwZGEwMzRiNTM4MzRlMzQ4MmIzZjkwZmZlM2NjODUxZmJjNDI1OTcxNDAyMmZlNmFjODZlNTg0YWM

**Comment by juanjux** [comment]
Thanks!
