### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by grafiktr** [bblfsh/documentation#147]
Hello! I make a living by translating articles, lectures and some other documents English to Turkish or Turkish to English. I would like to help you to translate your project to Turkish. If you download the Licence document and give me a permission to do so, I would be really appreciated to help you. Thank you in advanced...

**Comment by juanjux** [comment]
Hi @grafiktr!

Thank you for your kind offer! Unfortunately I don't think that at this development stage of the project, with frequent and notable changes both in the code and the documentation,  we could manage to maintain translations and kept them synced in a reasonable way. But maybe we could cooperate in the future in that direction.
