### ISSUE TITLE
Update and auto-generate roles list

### ISSUE THREAD

**Issue by dennwc** [bblfsh/documentation#152]
We should keep [./uast/roles.md](https://github.com/bblfsh/documentation/blob/master/uast/roles.md) file updated by auto-generating it from SDK sources and by examining available drivers.

**Comment by juanjux** [comment]
Rules have a `String` method that can generate an XPath-like string. This was used in the path for a `make docgen` command that called `go run driver/main.go docgen`, which just called `fmt.Println(Driver.Annotate)`. 

This was removed in october for reason that I don't remember (the commit says "remove broken docgen" so probably didn't work after the rewrite and it wasn't deemed interesting enough to re-implement it), but to String method still exist so it could probably be used or modified to implement this (plus an autoupdate system in the documentation project).

**Comment by dennwc** [comment]
The script used to generate an original list (by @mcuadros):
https://gist.github.com/dennwc/0d5f9f5fdb49e0209e711e07e7bb3654
It seems like the only thing we need to change is to let it discover driver lists as other our tools do.
