### ISSUE TITLE
The build example does not work

### ISSUE THREAD

**Issue by alcortesm** [bblfsh/documentation#16]
The build example recommends this steps:
```
# build SDK
go get -u github.com/bblfsh/sdk/...

# build a driver + container
git clone https://github.com/bblfsh/java-driver.git
go get -v -t ./...
make build
```
If I follow them, I get an error in the last one (`make build`):
```
; make build
Makefile:3: *** You must install bblfsh-sdk.  Stop.
```

I think the problem is that the `.sdk` directory is missing and the error reporting is misleading.

According to `https://github.com/bblfsh/java-driver/blob/master/README.md` a `bblfsh-sdk pre-build` is needed to generate the `.sdk` directory.

**Comment by eiso** [comment]
The documentation is updated, @smola I think this can be closed.
