### ISSUE TITLE
mermaid diagrams are not rendered

### ISSUE THREAD

**Issue by juanjux** [bblfsh/documentation#163]
Example:

https://docs.sourced.tech/babelfish/uast/uast-specification

**Comment by bzz** [comment]
We use https://mermaidjs.github.io/ JS to render the diagrams, so there must be some gitbook.io plugin that got broken on their side (like [this one](https://github.com/bblfsh/documentation/blob/5a386770fb365540476c0112764708ce67c876df/.travis.yml#L11)) that needs to be fixed.

**Comment by juanjux** [comment]
Yes, there was a plugin configured (@smola had the configuration somewhere in his settings), so we should find an alternative or open and issue/fix it upstream  or generate the diagrams in an image format.

I will take a look at this once I'm done with the C++ driver.

**Comment by smola** [comment]
gitbook 2 does not support plugins, so mermaid diagrams need to be dropped. Diagrams will need to be generated to PNG from source are checked in into the repository.

**Comment by juanjux** [comment]
Working on this.
