### ISSUE TITLE
Text improvement on clients documentation 

### ISSUE THREAD

**Issue by tsolakoua** [bblfsh/documentation#187]
In the [clients](https://doc.bblf.sh/using-babelfish/language-clients.html) guide: 

 ``` The client API's differ to adapt to their language specific idioms, the following [codes] [shows] several simple examples with the Go, Python and Scala clients that [parsers] a file and [applies] a filter to return all the simple identifiers. ```

-  I don't know if it's correct in english using the plural ```codes```. Maybe it could be replaced with ```code snippets``` for example. 
- ```shows``` should be ```show``` also
-  ```parsers``` -> ```parse```
-  ``` applies ``` -> ```apply```

As I'm not native english speaker, every time I mention something non-trivial please double-check if possible in case I am wrong.

**Comment by juanjux** [comment]
You're right, source codes is super ugly, I'll fix it soon.
