### ISSUE TITLE
Rename "Language Clients" section

### ISSUE THREAD

**Issue by smola** [bblfsh/documentation#189]
From @ajnavarro yesterday ([more](https://github.com/ajnavarro/dupes/blob/master/empathy-log.md)):

> * Next documentation point: Language clients
>   * _a little bit strange name for bblfsh clients_

It is true that "Language Clients" might be confused and it could be just "Clients".

What do you think?

**Comment by juanjux** [comment]
I agree. Language client sound like a client for querying a specific programming language, which they're not.
