### ISSUE TITLE
Clarify about `@pos`, `uast:Position`, `uast:Positions`

### ISSUE THREAD

**Issue by zurk** [bblfsh/documentation#204]
https://github.com/bblfsh/documentation/blob/master/uast/semantic-uast.md contains 3 ways to deal with position information: `@pos`, `uast:Position`, `uast:Positions` and to be honest I do not get the difference from the doc. And when I should use what.

Can we clarify it?

**Comment by juanjux** [comment]
Fixed by #213.

I'll also add, in a separate PR, a commented example of UAST v2.
