### ISSUE TITLE
No information about available drivers versions

### ISSUE THREAD

**Issue by zurk** [bblfsh/documentation#209]
Once I need to use another driver (for example last v1 driver for python) I should go to https://hub.docker.com/r/bblfsh/python-driver/tags/ and check its version. It is kind of fine to have it there, but there are no links to docker hub in the bblfsh doc. I think it is worth to add it.

**Comment by juanjux** [comment]
There are links in the language pages, in the "Container" tick mark.

**Comment by zurk** [comment]
Excuse me, but where? I cannot find.
