### ISSUE TITLE
Document how UAST structure may change across versions

### ISSUE THREAD

**Issue by creachadair** [bblfsh/documentation#228]
Clients that consume UASTs may be very sensitive to small perturbations in the structure of the tree (see http://www.hyrumslaw.com/). However, in order to add new features to language drivers, we need the ability to make changes that will be visible in both the native and canonicalized UASTs.

As far as I can tell, we do not currently have any specification for what changes are allowed within the context of a version update. In principle we use semantic versioning for drivers, but if any change to the UAST output could potentially be breaking, the version numbers do not help. We should define a contract for what kinds of changes are allowed at the various levels of versioning. Ideally when we ship new driver revisions, we could then also provide a set of "compatibility-regression" tests, that prove (or at least support) the conclusion that the change is "safe" for a given revision change.

Implementing this will almost certainly require more design and subparts. If we can agree on the outlines, we might consider creating a milestone for it.

**Comment by juanjux** [comment]
We have the integration tests that are checked on Travis. Usually we don't change the structure of the UAST outside of bugfixes but versioning (even for bugfixes) would be good to have.

**Comment by creachadair** [comment]
> We have the integration tests that are checked on Travis. Usually we don't change the structure of the UAST outside of bugfixes but versioning (even for bugfixes) would be good to have.

Yes. And even when we don't change the overall structure, adding new node kinds and properties affects the API surface that the client cares about, so having versions helps. But I think we also need to have some rules about what counts as a "breaking" change and what the clients will have to be robust to (e.g., a client shouldn't fail if we add a new property, but may need to know if we rename something).
