### ISSUE TITLE
Call for Ideas for Summer of Code 2019

### ISSUE THREAD

**Issue by bzz** [bblfsh/documentation#229]
GSoC 2019 organization application CfP period is until Feb 6th and I once again #132 thought  Bblfsh project might benefit from participation, so why do not we start gathering preliminary project ideas?

So far the most prominent idea that was discussed (keeping this issue updated)
 - implement a driver for some (new) language (1 student)
 - rootless bblfshd

Reason for `adding a driver` being most prominent: it's quite self-contained pice of functionality, relies on more or less stable API and as a first time org the goal of 1 student is very reasonable for the program as a whole.

What do you guys think @dennwc @mcuadros @smola @campoy ?

If there are no objections, I would be happy to take a stab and share a draft of the Bblfsh org application here early next week. That should not take a lot of time, given my previous experience of serving as a GSoC mentor and an org admin for ASF.

**Comment by creachadair** [comment]
I think it's a good idea. In addition too giving someone an interesting learning-project to work on, it would increase our visibility, and help us shake out contributor issues.

**Comment by juanjux** [comment]
Great idea! I agree a driver is a good place to work o start, probably the suggested PL/SQL, Cobol or Typescript.

**Comment by creachadair** [comment]
> Great idea! I agree a driver is a good place to work o start, probably the suggested PL/SQL, Cobol or Typescript.

I suspect we won't want to wait for PL/SQL till summer, but TypeScript certainly seems like a good candidate.

**Comment by bzz** [comment]
Things to fill in:
```
# short description
Babelfish is a self-hosted server for source code parsing

# long description
Babelfish is a self-hosted server for source code parsing. The Babelfish service can parse any file, in any supported language, extracting an Abstract Syntax Tree (AST) from it and converting it into a Universal Abstract Syntax Tree (UAST). It was created as a solution for large scale code analysis

# application Instructions
<Guidance for students on how to apply to your organization. Should include any prerequisites or requirements. You may wish to include a template or tips for their proposals>

# contact methods
Chat:
Mailing List:
General Email:

# Application
Why does your org want to participate in Google Summer of Code?

How will you keep mentors engaged with their students?

How will you help your students stay on schedule to complete their projects?

How will you get your students involved in your community during GSoC?

How will you keep students involved with your community after GSoC?

Reference point
<If you are a new organization to GSoC, is there a Google employee or previously participating organization who will vouch for you? If so, please enter their name, contact email, and relationship to your organization>

Anything else we should know (optional)?

GSoC Org Admins
 - 
 - 
```

**Comment by bzz** [comment]
Application submitted, further project ideas are aggregated under https://github.com/bblfsh/documentation/wiki/GSoC-2019-Ideas and now we also have a mint Mailing List https://groups.google.com/forum/#!forum/bblfsh-dev 🚀
