### ISSUE TITLE
Create a user-oriented guide/tutorial on how UAST maps to XPath queries

### ISSUE THREAD

**Issue by creachadair** [bblfsh/documentation#234]
Arose from discussion in https://github.com/src-d/minutes/pull/476.

Because the structure of a UAST is fairly complex, it can be difficult for users trying to write XPath queries over UASTs to understand how to map their intuitive understanding of the structure to a concrete query. In particular, bblfsh does some tricks in mapping the UAST (which is not really a pure tree and contains meta-structure) into an XML-like surface, which are not obvious.

We should provide a combination of tutorial and medium-level reference guide to how UAST XPath queries work, including specific examples as much as possible (ideally, based on real queries that people have asked us about if we can reduce them sufficiently).

**Comment by bzz** [comment]
Just my .05$ - as a user, I would be grateful if such doc explicitly differentiates Annotated (v1) and Semantic (v2) cases.

**Comment by dennwc** [comment]
...and Annotated (v2). Everything in v2 has a slightly different XML projection, assuming the new `libuast` is used.

**Comment by creachadair** [comment]
I think it would be OK to concentrate most of our effort on the v2 mappings. While there are still users of v1, it would make sense to invest in documentation that makes the migration easier.
