### ISSUE TITLE
Clarify UASTv2 status

### ISSUE THREAD

**Issue by mcarmonaa** [bblfsh/documentation#236]
Related to the empathy session.

From the source{d} intro documentation you can get directly to https://docs.sourced.tech/babelfish/uast/uast-specification. From this page is not clear what is the status of UASTv1/UASTv2. Maybe a link to https://docs.sourced.tech/babelfish/#current-status would be helpful or even make the content of this talk about v2 and left a link to the legacy v1 instead of the other way.

**Comment by creachadair** [comment]
I believe this should be addressed by #240. If I have missed anything you wanted to have addressed, feel free to reopen it and let me know.
