### ISSUE TITLE
Implement driver's versions updater

### ISSUE THREAD

**Issue by lwsanty** [bblfsh/documentation#275]
We need a job that will update drivers versions in documentation once in a period(around a week).
Job should:
- get the list of versions of maintained drivers
- update the ones whos version was changed
- prepare related PR with changes.

Jenkins is more probably to be used.

**Comment by dennwc** [comment]
I think the easier approach would be to call `make languages` once a week and commit/PR if there are any changes. This script already gets the list of drivers, etc.
