### ISSUE TITLE
Add simple comparison table for alternatives

### ISSUE THREAD

**Issue by bzz** [bblfsh/documentation#35]
It would be nice to have a page where Babelfish is briefly compared with other similar efforts. Highlighting key differences would help people from other communities get interested in Babelfish as well as provide better understanding of possible solutions "landscape".

Other efforts worth comparing to:
 - [Microsoft/language-server-protocol](https://github.com/Microsoft/language-server-protocol) and [LSP Implementations](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations)
 - [sourcegraph/srclib](https://github.com/sourcegraph/srclib)
 - [ctags](http://ctags.sourceforge.net/)
 - http://kythe.io

Something like https://github.com/OpenGrok/OpenGrok/wiki/Comparison-with-Similar-Tools or even simpler - a paragraph about each tool would be great. 

What would be the best place for such page? If you guys see value in this - I'll be happy to allocate some time and contribute a first draft.

**Comment by smola** [comment]
Also, look at Hashicorp projects, which usually have a dedicated section to this:
https://www.consul.io/intro/vs/index.html
https://www.vagrantup.com/intro/vs/index.html

**Comment by bzz** [comment]
Could be nice to include
 - https://github.com/antlr/antlr4
 - https://github.com/tree-sitter/tree-sitter

**Comment by abeaumont** [comment]
Also:
* http://www.srcml.org/
* https://github.com/ThierryGoubier/SmaCC

**Comment by dennwc** [comment]
Fixed in #155
